FROM python:3.12-slim

WORKDIR /app

RUN pip install --no-cache-dir \
    flask \
    torch \
    mlflow

COPY app.py .

ENV MLFLOW_TRACKING_URI=http://mlflow:5000
ENV PYTHONUNBUFFERED=1

EXPOSE 8000

CMD ["python", "app.py"]